'use strict';

const REQUEST_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

// Valid transitions: what status can move to what
const VALID_TRANSITIONS = {
  [REQUEST_STATUS.PENDING]: [REQUEST_STATUS.ACCEPTED, REQUEST_STATUS.CANCELLED],
  [REQUEST_STATUS.ACCEPTED]: [REQUEST_STATUS.IN_PROGRESS],
  [REQUEST_STATUS.IN_PROGRESS]: [REQUEST_STATUS.COMPLETED],
  [REQUEST_STATUS.COMPLETED]: [],
  [REQUEST_STATUS.CANCELLED]: [],
};

const ROLES = {
  TOURIST: 'TOURIST',
  WHEELCHAIR_ATTENDANT: 'WHEELCHAIR_ATTENDANT',
  ADMIN: 'ADMIN',
  STATION_STAFF: 'STATION_STAFF',
};

const AUDIT_ACTIONS = {
  CREATED: 'CREATED',
  ACCEPTED: 'ACCEPTED',
  STATUS_UPDATED: 'STATUS_UPDATED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

module.exports = { REQUEST_STATUS, VALID_TRANSITIONS, ROLES, AUDIT_ACTIONS };
